# Generated by Django 4.2.16 on 2024-09-30 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_review_user'),
        ('appointments', '0002_alter_appointment_user'),
        ('users', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
